In [11]:
import pandas as pd

In [12]:
import pandas as pd

s = pd.Series([10, 20, 30], index=["A", "B", "C"])

print(s)
print(s["B"])

A    10
B    20
C    30
dtype: int64
20

In [13]:
import pandas as pd

s = pd.Series([10, 20, 30])

print(s.values)   # NumPy array

[10 20 30]

In [14]:
import pandas as pd

data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]

df2 = pd.DataFrame(data_list)
print(df2)

       0   1         2      3
0   John  28  New York  65000
1   Anna  34     Paris  70000
2  Peter  29    Berlin  62000
3  Linda  42    London  85000

In [15]:

columns = ["Name", "Age", "City", "Salary"]
rows = ["A", "B", "C", "D"]

df2 = pd.DataFrame(data_list, columns=columns, index=rows)

print(df2)

    Name  Age      City  Salary
A   John   28  New York   65000
B   Anna   34     Paris   70000
C  Peter   29    Berlin   62000
D  Linda   42    London   85000

In [16]:
df2[["Name", "Age"]]

    Name  Age
A   John   28
B   Anna   34
C  Peter   29
D  Linda   42

In [17]:
rows = []
for i in range(len(data_list)):
    rows.append(f"Row{i+1}")

df2 = pd.DataFrame(data_list, columns=columns, index=rows)

print(df2)

       Name  Age      City  Salary
Row1   John   28  New York   65000
Row2   Anna   34     Paris   70000
Row3  Peter   29    Berlin   62000
Row4  Linda   42    London   85000

In [18]:
df2["Designation"] = ["Engineer", "Manager", "Analyst", "Director"]

In [19]:
df2

       Name  Age      City  Salary Designation
Row1   John   28  New York   65000    Engineer
Row2   Anna   34     Paris   70000     Manager
Row3  Peter   29    Berlin   62000     Analyst
Row4  Linda   42    London   85000    Director

In [20]:
df2.loc[df2["Name"] == "Anna"]

      Name  Age   City  Salary Designation
Row2  Anna   34  Paris   70000     Manager

In [21]:
df2.iloc[[1]]

      Name  Age   City  Salary Designation
Row2  Anna   34  Paris   70000     Manager

selecting rows and columns

In [22]:
df2.loc[[2,3]][["Name", "Age"]]

KeyError: "None of [Index([2, 3], dtype='int64')] are in the [index]"

In [23]:
df2[(df2["Age"] > 30) & (df2["Salary"] > 70000)]

       Name  Age    City  Salary Designation
Row4  Linda   42  London   85000    Director

MISSING DATA

In [25]:
import pandas as pd
import numpy as np

data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [np.nan, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}

df = pd.DataFrame(data)

print(df)

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
2  NaN  3.0  3.0  NaN
3  4.0  4.0  NaN  NaN
4  5.0  5.0  NaN  5.0

In [26]:
df.isna().sum()

A    1
B    1
C    2
D    3
dtype: int64

In [27]:
df.isna().any()

A    True
B    True
C    True
D    True
dtype: bool

In [29]:
df.dropna(thresh=3)

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
4  5.0  5.0  NaN  5.0

In [30]:
df.fillna(0)

     A    B    C    D
0  1.0  0.0  1.0  1.0
1  2.0  2.0  2.0  0.0
2  0.0  3.0  3.0  0.0
3  4.0  4.0  0.0  0.0
4  5.0  5.0  0.0  5.0

In [37]:
value={'A': 0, 'B': 1, 'C': 2, 'D': 3}
df.fillna(value=value)

     A    B    C    D
0  1.0  1.0  1.0  1.0
1  2.0  2.0  2.0  3.0
2  0.0  3.0  3.0  3.0
3  4.0  4.0  2.0  3.0
4  5.0  5.0  2.0  5.0

In [35]:
df

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
2  NaN  3.0  3.0  NaN
3  4.0  4.0  NaN  NaN
4  5.0  5.0  NaN  5.0

In [38]:
import pandas as pd

# DataFrame 1: Employee information
employees = pd.DataFrame({
    'employee_id': [1, 2, 3, 4, 5],
    'name': ['John', 'Anna', 'Peter', 'Linda', 'Bob'],
    'department': ['HR', 'IT', 'Finance', 'IT', 'HR']
})

# DataFrame 2: Salary information
salaries = pd.DataFrame({
    'employee_id': [1, 2, 3, 6, 7],
    'salary': [60000, 80000, 65000, 70000, 90000],
    'bonus': [5000, 10000, 7000, 8000, 12000]
})

In [39]:
employees

   employee_id   name department
0            1   John         HR
1            2   Anna         IT
2            3  Peter    Finance
3            4  Linda         IT
4            5    Bob         HR

In [40]:
salaries

   employee_id  salary  bonus
0            1   60000   5000
1            2   80000  10000
2            3   65000   7000
3            6   70000   8000
4            7   90000  12000

In [41]:
pd.merge(employees, salaries, on='employee_id', how='inner')

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000

In [42]:
pd.merge(employees, salaries, on='employee_id', how='outer')

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN
5            6    NaN        NaN  70000.0   8000.0
6            7    NaN        NaN  90000.0  12000.0

In [43]:
pd.merge(employees, salaries, on='employee_id', how='left')

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN

In [44]:
pd.merge(employees, salaries, on='employee_id', how='right')

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000
3            6    NaN        NaN   70000   8000
4            7    NaN        NaN   90000  12000

In [45]:
import pandas as pd

df = pd.DataFrame({
    "Department": ["HR", "IT", "IT", "Finance", "HR", "Finance"],
    "Employee": ["John", "Anna", "Peter", "Bob", "Linda", "Tom"],
    "Salary": [50000, 70000, 65000, 80000, 55000, 90000],
    "Experience": [2, 5, 4, 8, 3, 10]
})

print(df)

  Department Employee  Salary  Experience
0         HR     John   50000           2
1         IT     Anna   70000           5
2         IT    Peter   65000           4
3    Finance      Bob   80000           8
4         HR    Linda   55000           3
5    Finance      Tom   90000          10

In [ ]:
df.groupby("Department")["Salary"].sum()

Department
Finance    170000
HR         105000
IT         135000
Name: Salary, dtype: int64

In [49]:
df.groupby("Department")["Salary"].mean()

Department
Finance    85000.0
HR         52500.0
IT         67500.0
Name: Salary, dtype: float64

In [50]:
df.groupby("Department")["Salary"].agg(["sum", "mean", "min", "max", "count"])

               sum     mean    min    max  count
Department
Finance     170000  85000.0  80000  90000      2
HR          105000  52500.0  50000  55000      2
IT          135000  67500.0  65000  70000      2